engines:
  fixme:
    enabled: true
  jscpd:
    enabled: true
  radon:
    enabled: true
ratings:
  paths: 
    - "**.cs"
exclude_paths: 
  - "README.md"
  - "ActionRpgKit/Tests/Story/storyline.xml"
  - "config.dox"
  - "generateDocumentationAndDeploy.sh"
  - ".gitignore"
  - "ActionRpgKit.sln"
  - "ActionRpgKit/ActionRpgKit.csproj"
