language: csharp
solution: ActionRpgKit.sln
install:
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
  - nuget restore ActionRpgKit.sln
script:
  - xbuild /p:Configuration=Release ActionRpgKit.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe 
