var annotated =
[
    [ "BaseCharacter", "d7/d90/class_action_rpg_kit_1_1_core_1_1_character_1_1_base_character.xhtml", "d7/d90/class_action_rpg_kit_1_1_core_1_1_character_1_1_base_character" ],
    [ "BaseItem", "df/d58/class_action_rpg_kit_1_1_core_1_1_item_1_1_base_item.xhtml", "df/d58/class_action_rpg_kit_1_1_core_1_1_item_1_1_base_item" ],
    [ "BaseObjective", "d5/d59/class_action_rpg_kit_1_1_core_1_1_quest_1_1_base_objective.xhtml", "d5/d59/class_action_rpg_kit_1_1_core_1_1_quest_1_1_base_objective" ],
    [ "BaseQuest", "d2/d53/class_action_rpg_kit_1_1_core_1_1_quest_1_1_base_quest.xhtml", "d2/d53/class_action_rpg_kit_1_1_core_1_1_quest_1_1_base_quest" ],
    [ "BaseSkill", "d8/ddb/class_action_rpg_kit_1_1_core_1_1_character_1_1_skill_1_1_base_skill.xhtml", "d8/ddb/class_action_rpg_kit_1_1_core_1_1_character_1_1_skill_1_1_base_skill" ],
    [ "BaseStats", "de/dd8/class_action_rpg_kit_1_1_core_1_1_character_1_1_stats_1_1_base_stats.xhtml", "de/dd8/class_action_rpg_kit_1_1_core_1_1_character_1_1_stats_1_1_base_stats" ],
    [ "Enemy", "d0/da7/class_action_rpg_kit_1_1_core_1_1_character_1_1_enemy.xhtml", "d0/da7/class_action_rpg_kit_1_1_core_1_1_character_1_1_enemy" ],
    [ "EnemyStats", "df/d6b/class_action_rpg_kit_1_1_core_1_1_character_1_1_stats_1_1_enemy_stats.xhtml", "df/d6b/class_action_rpg_kit_1_1_core_1_1_character_1_1_stats_1_1_enemy_stats" ],
    [ "GameTime", "d9/db6/class_game_time.xhtml", "d9/db6/class_game_time" ],
    [ "IAttribute", "db/d8f/interface_action_rpg_kit_1_1_core_1_1_character_1_1_attribute_1_1_i_attribute.xhtml", "db/d8f/interface_action_rpg_kit_1_1_core_1_1_character_1_1_attribute_1_1_i_attribute" ],
    [ "ICharacter", "dc/d2f/interface_action_rpg_kit_1_1_core_1_1_character_1_1_i_character.xhtml", "dc/d2f/interface_action_rpg_kit_1_1_core_1_1_character_1_1_i_character" ],
    [ "ICombatSkill", "d1/d42/interface_action_rpg_kit_1_1_core_1_1_character_1_1_skill_1_1_i_combat_skill.xhtml", "d1/d42/interface_action_rpg_kit_1_1_core_1_1_character_1_1_skill_1_1_i_combat_skill" ],
    [ "IFighter", "d6/d4d/interface_action_rpg_kit_1_1_core_1_1_character_1_1_i_fighter.xhtml", "d6/d4d/interface_action_rpg_kit_1_1_core_1_1_character_1_1_i_fighter" ],
    [ "IItem", "d8/d71/interface_action_rpg_kit_1_1_core_1_1_item_1_1_i_item.xhtml", "d8/d71/interface_action_rpg_kit_1_1_core_1_1_item_1_1_i_item" ],
    [ "IMagicSkill", "db/d74/interface_action_rpg_kit_1_1_core_1_1_character_1_1_skill_1_1_i_magic_skill.xhtml", "db/d74/interface_action_rpg_kit_1_1_core_1_1_character_1_1_skill_1_1_i_magic_skill" ],
    [ "IMagicUser", "d9/d26/interface_action_rpg_kit_1_1_core_1_1_character_1_1_i_magic_user.xhtml", "d9/d26/interface_action_rpg_kit_1_1_core_1_1_character_1_1_i_magic_user" ],
    [ "IModifier", "d6/da5/interface_action_rpg_kit_1_1_core_1_1_character_1_1_attribute_1_1_i_modifier.xhtml", "d6/da5/interface_action_rpg_kit_1_1_core_1_1_character_1_1_attribute_1_1_i_modifier" ],
    [ "IObjective", "d2/d58/interface_action_rpg_kit_1_1_core_1_1_quest_1_1_i_objective.xhtml", "d2/d58/interface_action_rpg_kit_1_1_core_1_1_quest_1_1_i_objective" ],
    [ "IQuest", "de/df7/interface_action_rpg_kit_1_1_core_1_1_quest_1_1_i_quest.xhtml", "de/df7/interface_action_rpg_kit_1_1_core_1_1_quest_1_1_i_quest" ],
    [ "ISkill", "dd/dd7/interface_action_rpg_kit_1_1_core_1_1_character_1_1_skill_1_1_i_skill.xhtml", "dd/dd7/interface_action_rpg_kit_1_1_core_1_1_character_1_1_skill_1_1_i_skill" ],
    [ "MeleeSkill", "de/d14/class_action_rpg_kit_1_1_core_1_1_character_1_1_skill_1_1_melee_skill.xhtml", "de/d14/class_action_rpg_kit_1_1_core_1_1_character_1_1_skill_1_1_melee_skill" ],
    [ "PassiveMagicSkill", "d6/d2c/class_action_rpg_kit_1_1_core_1_1_character_1_1_skill_1_1_passive_magic_skill.xhtml", "d6/d2c/class_action_rpg_kit_1_1_core_1_1_character_1_1_skill_1_1_passive_magic_skill" ],
    [ "Player", "db/d7e/class_action_rpg_kit_1_1_core_1_1_character_1_1_player.xhtml", "db/d7e/class_action_rpg_kit_1_1_core_1_1_character_1_1_player" ],
    [ "PlayerStats", "dd/dcb/class_action_rpg_kit_1_1_core_1_1_character_1_1_stats_1_1_player_stats.xhtml", "dd/dcb/class_action_rpg_kit_1_1_core_1_1_character_1_1_stats_1_1_player_stats" ],
    [ "PrimaryAttribute", "da/da1/class_action_rpg_kit_1_1_core_1_1_character_1_1_attribute_1_1_primary_attribute.xhtml", "da/da1/class_action_rpg_kit_1_1_core_1_1_character_1_1_attribute_1_1_primary_attribute" ],
    [ "SecondaryAttribute", "d7/d09/class_action_rpg_kit_1_1_core_1_1_character_1_1_attribute_1_1_secondary_attribute.xhtml", "d7/d09/class_action_rpg_kit_1_1_core_1_1_character_1_1_attribute_1_1_secondary_attribute" ],
    [ "SimpleVolumeAttribute", "dc/d20/class_action_rpg_kit_1_1_core_1_1_character_1_1_attribute_1_1_simple_volume_attribute.xhtml", "dc/d20/class_action_rpg_kit_1_1_core_1_1_character_1_1_attribute_1_1_simple_volume_attribute" ],
    [ "TimeBasedModifier", "dd/d62/class_action_rpg_kit_1_1_core_1_1_character_1_1_attribute_1_1_time_based_modifier.xhtml", "dd/d62/class_action_rpg_kit_1_1_core_1_1_character_1_1_attribute_1_1_time_based_modifier" ],
    [ "VolumeAttribute", "d3/da5/class_action_rpg_kit_1_1_core_1_1_character_1_1_attribute_1_1_volume_attribute.xhtml", "d3/da5/class_action_rpg_kit_1_1_core_1_1_character_1_1_attribute_1_1_volume_attribute" ]
];