version: 1.0.{build}
skip_tags: true
configuration: Debug
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  COVERALLS_REPO_TOKEN:
    secure: LB6jKHcKcWky5k+vY2yxExfQ0uv50v5E1K533gq/ByPiwdipFlS29E6/NF890doz
before_build:
  - nuget restore "./src/ActionRpgKit.sln"
build:
  project: /src/ActionRpgKit.sln
  verbosity: minimal
after_test:
  - cmd: .\after_test.cmd




