version: 0.0.{build}
configuration: Release
environment:
  COVERALLS_REPO_TOKEN:
    secure: ccQ+As60wXwW+67I7IMmQUlt+z2qXhI4GKLsbMPr13JitDr3MLgx8jXcGCZCfrMm
before_build:
  - nuget restore 
after_test:
  - cmd: .\after_test.cmd
