var annotated =
[
    [ "BaseCharacter", "d9/d5c/class_action_rpg_kit_1_1_character_1_1_base_character.xhtml", "d9/d5c/class_action_rpg_kit_1_1_character_1_1_base_character" ],
    [ "BaseItem", "df/d58/class_action_rpg_kit_1_1_core_1_1_item_1_1_base_item.xhtml", "df/d58/class_action_rpg_kit_1_1_core_1_1_item_1_1_base_item" ],
    [ "BaseObjective", "d5/d59/class_action_rpg_kit_1_1_core_1_1_quest_1_1_base_objective.xhtml", "d5/d59/class_action_rpg_kit_1_1_core_1_1_quest_1_1_base_objective" ],
    [ "BaseQuest", "d2/d53/class_action_rpg_kit_1_1_core_1_1_quest_1_1_base_quest.xhtml", "d2/d53/class_action_rpg_kit_1_1_core_1_1_quest_1_1_base_quest" ],
    [ "BaseSkill", "dc/db7/class_action_rpg_kit_1_1_character_1_1_skill_1_1_base_skill.xhtml", "dc/db7/class_action_rpg_kit_1_1_character_1_1_skill_1_1_base_skill" ],
    [ "BaseStats", "db/dd8/class_action_rpg_kit_1_1_character_1_1_stats_1_1_base_stats.xhtml", "db/dd8/class_action_rpg_kit_1_1_character_1_1_stats_1_1_base_stats" ],
    [ "Enemy", "d2/df0/class_action_rpg_kit_1_1_character_1_1_enemy.xhtml", "d2/df0/class_action_rpg_kit_1_1_character_1_1_enemy" ],
    [ "EnemyStats", "df/d7d/class_action_rpg_kit_1_1_character_1_1_stats_1_1_enemy_stats.xhtml", "df/d7d/class_action_rpg_kit_1_1_character_1_1_stats_1_1_enemy_stats" ],
    [ "GameTime", "d9/db6/class_game_time.xhtml", "d9/db6/class_game_time" ],
    [ "IAttribute", "d5/d7e/interface_action_rpg_kit_1_1_character_1_1_attribute_1_1_i_attribute.xhtml", "d5/d7e/interface_action_rpg_kit_1_1_character_1_1_attribute_1_1_i_attribute" ],
    [ "ICharacter", "d2/df8/interface_action_rpg_kit_1_1_character_1_1_i_character.xhtml", "d2/df8/interface_action_rpg_kit_1_1_character_1_1_i_character" ],
    [ "ICombatSkill", "d4/dbe/interface_action_rpg_kit_1_1_character_1_1_skill_1_1_i_combat_skill.xhtml", "d4/dbe/interface_action_rpg_kit_1_1_character_1_1_skill_1_1_i_combat_skill" ],
    [ "IFighter", "df/d5e/interface_action_rpg_kit_1_1_character_1_1_i_fighter.xhtml", "df/d5e/interface_action_rpg_kit_1_1_character_1_1_i_fighter" ],
    [ "IItem", "d8/d71/interface_action_rpg_kit_1_1_core_1_1_item_1_1_i_item.xhtml", "d8/d71/interface_action_rpg_kit_1_1_core_1_1_item_1_1_i_item" ],
    [ "IMagicSkill", "d7/dd4/interface_action_rpg_kit_1_1_character_1_1_skill_1_1_i_magic_skill.xhtml", "d7/dd4/interface_action_rpg_kit_1_1_character_1_1_skill_1_1_i_magic_skill" ],
    [ "IMagicUser", "dd/db0/interface_action_rpg_kit_1_1_character_1_1_i_magic_user.xhtml", "dd/db0/interface_action_rpg_kit_1_1_character_1_1_i_magic_user" ],
    [ "IModifier", "d5/dc3/interface_action_rpg_kit_1_1_character_1_1_attribute_1_1_i_modifier.xhtml", "d5/dc3/interface_action_rpg_kit_1_1_character_1_1_attribute_1_1_i_modifier" ],
    [ "IObjective", "d2/d58/interface_action_rpg_kit_1_1_core_1_1_quest_1_1_i_objective.xhtml", "d2/d58/interface_action_rpg_kit_1_1_core_1_1_quest_1_1_i_objective" ],
    [ "IQuest", "de/df7/interface_action_rpg_kit_1_1_core_1_1_quest_1_1_i_quest.xhtml", "de/df7/interface_action_rpg_kit_1_1_core_1_1_quest_1_1_i_quest" ],
    [ "ISkill", "d5/dc7/interface_action_rpg_kit_1_1_character_1_1_skill_1_1_i_skill.xhtml", "d5/dc7/interface_action_rpg_kit_1_1_character_1_1_skill_1_1_i_skill" ],
    [ "MeleeSkill", "d4/d60/class_action_rpg_kit_1_1_character_1_1_skill_1_1_melee_skill.xhtml", "d4/d60/class_action_rpg_kit_1_1_character_1_1_skill_1_1_melee_skill" ],
    [ "PassiveMagicSkill", "dc/dac/class_action_rpg_kit_1_1_character_1_1_skill_1_1_passive_magic_skill.xhtml", "dc/dac/class_action_rpg_kit_1_1_character_1_1_skill_1_1_passive_magic_skill" ],
    [ "Player", "d7/dd8/class_action_rpg_kit_1_1_character_1_1_player.xhtml", "d7/dd8/class_action_rpg_kit_1_1_character_1_1_player" ],
    [ "PlayerStats", "d7/dbc/class_action_rpg_kit_1_1_character_1_1_stats_1_1_player_stats.xhtml", "d7/dbc/class_action_rpg_kit_1_1_character_1_1_stats_1_1_player_stats" ],
    [ "PrimaryAttribute", "d5/ddc/class_action_rpg_kit_1_1_character_1_1_attribute_1_1_primary_attribute.xhtml", "d5/ddc/class_action_rpg_kit_1_1_character_1_1_attribute_1_1_primary_attribute" ],
    [ "SecondaryAttribute", "df/d43/class_action_rpg_kit_1_1_character_1_1_attribute_1_1_secondary_attribute.xhtml", "df/d43/class_action_rpg_kit_1_1_character_1_1_attribute_1_1_secondary_attribute" ],
    [ "SimpleVolumeAttribute", "db/d9c/class_action_rpg_kit_1_1_character_1_1_attribute_1_1_simple_volume_attribute.xhtml", "db/d9c/class_action_rpg_kit_1_1_character_1_1_attribute_1_1_simple_volume_attribute" ],
    [ "TimeBasedModifier", "d5/d34/class_action_rpg_kit_1_1_character_1_1_attribute_1_1_time_based_modifier.xhtml", "d5/d34/class_action_rpg_kit_1_1_character_1_1_attribute_1_1_time_based_modifier" ],
    [ "VolumeAttribute", "d6/ddf/class_action_rpg_kit_1_1_character_1_1_attribute_1_1_volume_attribute.xhtml", "d6/ddf/class_action_rpg_kit_1_1_character_1_1_attribute_1_1_volume_attribute" ]
];